application: numeric-incline-526
version: 1
runtime: python27
instance_class: F4
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static
  application_readable: true

- url: /.*
  script: main.application

env_variables:
  DJANGO_SETTINGS_MODULE: 'website.settings'
  DATABASE_NAME: 'ocargo'

libraries:
- name: PIL
  version: latest
- name: MySQLdb
  version: latest
