application: numeric-incline-526
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static

- url: /.*
  script: main.application

env_variables:
  DJANGO_SETTINGS_MODULE: 'website.settings'
